/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jml_Mathx_Mathd */

#ifndef _Included_org_jml_Mathx_Mathd
#define _Included_org_jml_Mathx_Mathd
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jml_Mathx_Mathd_HALFPI
#define org_jml_Mathx_Mathd_HALFPI 1.5707963267948966
#undef org_jml_Mathx_Mathd_PI2
#define org_jml_Mathx_Mathd_PI2 6.283185307179586
#undef org_jml_Mathx_Mathd_TO_RADIANS
#define org_jml_Mathx_Mathd_TO_RADIANS 0.017453292519943295
#undef org_jml_Mathx_Mathd_TO_DEGREES
#define org_jml_Mathx_Mathd_TO_DEGREES 57.29577951308232
/*
 * Class:     org_jml_Mathx_Mathd
 * Method:    asinh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_jml_Mathx_Mathd_asinh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_jml_Mathx_Mathd
 * Method:    acosh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_jml_Mathx_Mathd_acosh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_jml_Mathx_Mathd
 * Method:    atanh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_jml_Mathx_Mathd_atanh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_jml_Mathx_Mathd
 * Method:    log2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_jml_Mathx_Mathd_log2
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
