/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mathx_Mathf */

#ifndef _Included_Mathx_Mathf
#define _Included_Mathx_Mathf
#ifdef __cplusplus
extern "C" {
#endif
#undef Mathx_Mathf_PI
#define Mathx_Mathf_PI 3.1415927f
#undef Mathx_Mathf_E
#define Mathx_Mathf_E 2.7182817f
#undef Mathx_Mathf_TO_RADIANS
#define Mathx_Mathf_TO_RADIANS 0.017453292f
#undef Mathx_Mathf_TO_DEGREES
#define Mathx_Mathf_TO_DEGREES 57.295776f
/*
 * Class:     Mathx_Mathf
 * Method:    sin
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_sin
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    cos
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_cos
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    tan
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_tan
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    asin
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_asin
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    acos
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_acos
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    atan
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_atan
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    atan2
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_atan2
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    sinh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_sinh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    cosh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_cosh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    tanh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_tanh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    asinh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_asinh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    acosh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_acosh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    atanh
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_atanh
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    pow
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_pow
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    exp
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_exp
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    expm1
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_expm1
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    log
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_log
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    log1p
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_log1p
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    log2
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_log2
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    log10
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_log10
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    sqrt
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_sqrt
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    cbrt
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_cbrt
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Mathx_Mathf
 * Method:    hypot
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Mathx_Mathf_hypot
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
