/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mathx_Extra_Shortx */

#ifndef _Included_Mathx_Extra_Shortx
#define _Included_Mathx_Extra_Shortx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mathx_Extra_Shortx
 * Method:    sum
 * Signature: (SS)S
 */
JNIEXPORT jbyte JNICALL Java_Mathx_Extra_Bytex_sum
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     Mathx_Extra_Shortx
 * Method:    subtr
 * Signature: (SS)S
 */
JNIEXPORT jbyte JNICALL Java_Mathx_Extra_Shortx_subtr
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     Mathx_Extra_Shortx
 * Method:    mul
 * Signature: (SS)S
 */
JNIEXPORT jbyte JNICALL Java_Mathx_Extra_Shortx_mul
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     Mathx_Extra_Shortx
 * Method:    div
 * Signature: (SS)S
 */
JNIEXPORT jbyte JNICALL Java_Mathx_Extra_Shortx_div
  (JNIEnv *, jclass, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
